# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-10-05 07:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pricepolicy',
            name='price',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='价格'),
        ),
    ]
