# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2021-10-10 01:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_wiki'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wiki',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='web.Wiki', verbose_name='父文章'),
        ),
    ]
